### ISSUE TITLE
make https://app.sfaudioguild.com/ redirect to https://app.sfaudioguild.com/login

### ISSUE THREAD

**Issue by mda100** [royalsaltmerchant/guild_login#13]
the "/" page is blank so make that page request redirect to the "/login" page

**Comment by mda100** [comment]
so when logged out in makes sense to make the root page redirect to the login page

but if someone is logged in already that has some unpredicted behavior 

so ill try to make it redirect to account page if logged in, login page if logged out

**Comment by mda100** [comment]
actually, I'll just open a separate issue to address the "/login" route when someone is already logged in (it shouldn't render the log in component, it should just say "already logged in" or something)

**Comment by royalsaltmerchant** [comment]
@mda100 just keep in mind that, when someone clicks on "Portal" at sfaudioguild.com it goes directly to "login". I'm open to that changing if necessary. I was also thinking about a page that says "access denied" if people try to manually go to the links if they are not logged in. Stuff to discuss, lets chat on the phone later.
