### ISSUE TITLE
Eternal Loading Screen

### ISSUE THREAD

**Issue by mda100** [royalsaltmerchant/guild_login#25]
if authenticate api call fails on login page, the authenticate function throws an error and the "loading" state is not changed, so it renders loading screen forever. Make it redirect to an error page.

**Comment by mda100** [comment]
hey @royalsaltmerchant - saw that you fixed the failed authenticate bug. Do you want me to make it redirect to an error page or anything (default rn is redirect to "not logged in" or "user info not found") ? if not, should we just close this issue?

**Comment by royalsaltmerchant** [comment]
@mda100 nah it's okay for now. Thanks for asking. Let's just close the issue.
