### ISSUE TITLE
dashboard routing -> access denied temporarily when adding contribution

### ISSUE THREAD

**Issue by mda100** [royalsaltmerchant/guild_login#28]
when logged in on dashboard
and a contribution is upload and then "complete" is submitted 
there is a white screen, then "Access Denied" very briefly, before it logs back into the logged in dashboard state

this is related to the routing/access PR #19 - i think when page refreshes default state says not logged in, then on "componentdidmount" in logs in automatically. solution would be to link this to the loading state/page as default before "componentdidmount" runs

this happens very quickly and is only noticeable when throttling network connection

Uploading Screen Recording 2021-09-10 at 4.18.00 PM.mov…

**Comment by royalsaltmerchant** [comment]
Maybe we can have the loading wheel show? Or does this happen even before the loading wheel? @mda100
